//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalHomeCinemaControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalHomeCinemaControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVR ERROR: {0}.
        /// </summary>
        internal static string FMT_AVR_ERROR {
            get {
                return ResourceManager.GetString("FMT_AVR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from {0}.
        /// </summary>
        internal static string FMT_DISCONNECTED {
            get {
                return ResourceManager.GetString("FMT_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDFURY ERROR: {0}.
        /// </summary>
        internal static string FMT_HDFURY_ERROR {
            get {
                return ResourceManager.GetString("FMT_HDFURY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to MPC: {0}.
        /// </summary>
        internal static string FMT_MPC_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("FMT_MPC_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network timeout connecting to {0}.
        /// </summary>
        internal static string FMT_NETWORK_TIMEOUT {
            get {
                return ResourceManager.GetString("FMT_NETWORK_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE ERROR: {0}.
        /// </summary>
        internal static string FMT_SCH_ERROR {
            get {
                return ResourceManager.GetString("FMT_SCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCP ERROR: {0}.
        /// </summary>
        internal static string FMT_SDCP_ERROR {
            get {
                return ResourceManager.GetString("FMT_SDCP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open serial connection on {0}.
        /// </summary>
        internal static string FMT_SERIAL_ERROR {
            get {
                return ResourceManager.GetString("FMT_SERIAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB failed to find result for {0}.
        /// </summary>
        internal static string FMT_TMDB_NO_RESULT {
            get {
                return ResourceManager.GetString("FMT_TMDB_NO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Closed.
        /// </summary>
        internal static string MSG_CONNECTION_CLOSED {
            get {
                return ResourceManager.GetString("MSG_CONNECTION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD Fury failed to set input..
        /// </summary>
        internal static string MSG_HDFURY_FAIL_INPUT_SELECT {
            get {
                return ResourceManager.GetString("MSG_HDFURY_FAIL_INPUT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action!.
        /// </summary>
        internal static string MSG_INVALID_ACTION {
            get {
                return ResourceManager.GetString("MSG_INVALID_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments!.
        /// </summary>
        internal static string MSG_INVALID_ARGS {
            get {
                return ResourceManager.GetString("MSG_INVALID_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Host.
        /// </summary>
        internal static string MSG_INVALID_HOST {
            get {
                return ResourceManager.GetString("MSG_INVALID_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Error!.
        /// </summary>
        internal static string MSG_IO_ERROR {
            get {
                return ResourceManager.GetString("MSG_IO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPC: Max errors exceeded, Exiting..
        /// </summary>
        internal static string MSG_MPC_MAX_ERRORS {
            get {
                return ResourceManager.GetString("MSG_MPC_MAX_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start MPC process!.
        /// </summary>
        internal static string MSG_MPC_START_ERROR {
            get {
                return ResourceManager.GetString("MSG_MPC_START_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected!.
        /// </summary>
        internal static string MSG_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("MSG_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object has been disposed..
        /// </summary>
        internal static string MSG_OBJECT_DISPOSED {
            get {
                return ResourceManager.GetString("MSG_OBJECT_DISPOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null.
        /// </summary>
        internal static string MSG_OBJECT_NULL {
            get {
                return ResourceManager.GetString("MSG_OBJECT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK..
        /// </summary>
        internal static string MSG_OK {
            get {
                return ResourceManager.GetString("MSG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value may not be less than 30.
        /// </summary>
        internal static string MSG_SDCP_DELAY_LESS_30 {
            get {
                return ResourceManager.GetString("MSG_SDCP_DELAY_LESS_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value may not be larger than 3200.
        /// </summary>
        internal static string MSG_SDCP_DELAY_MORE_3200 {
            get {
                return ResourceManager.GetString("MSG_SDCP_DELAY_MORE_3200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value length must be equal to 4 characters.
        /// </summary>
        internal static string MSG_SDCP_ERROR_COMMUNITY_LEN {
            get {
                return ResourceManager.GetString("MSG_SDCP_ERROR_COMMUNITY_LEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDCP OK..
        /// </summary>
        internal static string MSG_SDCP_OK {
            get {
                return ResourceManager.GetString("MSG_SDCP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream not readable or writable.
        /// </summary>
        internal static string MSG_STREAM_ERROR {
            get {
                return ResourceManager.GetString("MSG_STREAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval out of range..
        /// </summary>
        internal static string MSG_TIMER_INTERVAL_ERROR {
            get {
                return ResourceManager.GetString("MSG_TIMER_INTERVAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution out of range..
        /// </summary>
        internal static string MSG_TIMER_RESOLUTION_ERROR {
            get {
                return ResourceManager.GetString("MSG_TIMER_RESOLUTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key not set..
        /// </summary>
        internal static string MSG_TMDB_API_KEY_ERROR {
            get {
                return ResourceManager.GetString("MSG_TMDB_API_KEY_ERROR", resourceCulture);
            }
        }
    }
}
