//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalHomeCinemaManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class DeviceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DeviceSettings defaultInstance = ((DeviceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DeviceSettings())));
        
        public static DeviceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Source_Path {
            get {
                return ((string)(this["Source_Path"]));
            }
            set {
                this["Source_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Source_FullscreenDisplay {
            get {
                return ((int)(this["Source_FullscreenDisplay"]));
            }
            set {
                this["Source_FullscreenDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string Serial_Port {
            get {
                return ((string)(this["Serial_Port"]));
            }
            set {
                this["Serial_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Serial_ReadDelay {
            get {
                return ((int)(this["Serial_ReadDelay"]));
            }
            set {
                this["Serial_ReadDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int Serial_BaudRate {
            get {
                return ((int)(this["Serial_BaudRate"]));
            }
            set {
                this["Serial_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Parity Serial_Parity {
            get {
                return ((global::System.IO.Ports.Parity)(this["Serial_Parity"]));
            }
            set {
                this["Serial_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Serial_DataBits {
            get {
                return ((int)(this["Serial_DataBits"]));
            }
            set {
                this["Serial_DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits Serial_StopBits {
            get {
                return ((global::System.IO.Ports.StopBits)(this["Serial_StopBits"]));
            }
            set {
                this["Serial_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fd76b9a425ee4250b0bb70302ccb44e3")]
        public string MediaInfo_ApiKey {
            get {
                return ((string)(this["MediaInfo_ApiKey"]));
            }
            set {
                this["MediaInfo_ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Display_CommandDelay {
            get {
                return ((int)(this["Display_CommandDelay"]));
            }
            set {
                this["Display_CommandDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.6.66.111")]
        public string Display_Host {
            get {
                return ((string)(this["Display_Host"]));
            }
            set {
                this["Display_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53484")]
        public int Display_Port {
            get {
                return ((int)(this["Display_Port"]));
            }
            set {
                this["Display_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.6.66.101")]
        public string Processor_Host {
            get {
                return ((string)(this["Processor_Host"]));
            }
            set {
                this["Processor_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int Processor_Port {
            get {
                return ((int)(this["Processor_Port"]));
            }
            set {
                this["Processor_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Processor_HideUnusedOutputs {
            get {
                return ((bool)(this["Processor_HideUnusedOutputs"]));
            }
            set {
                this["Processor_HideUnusedOutputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.6.66.120")]
        public string InputSwitch_Host {
            get {
                return ((string)(this["InputSwitch_Host"]));
            }
            set {
                this["InputSwitch_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2210")]
        public int InputSwitch_Port {
            get {
                return ((int)(this["InputSwitch_Port"]));
            }
            set {
                this["InputSwitch_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection Display_CustomGamma {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Display_CustomGamma"]));
            }
            set {
                this["Display_CustomGamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection Display_CustomColorSpace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Display_CustomColorSpace"]));
            }
            set {
                this["Display_CustomColorSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection Display_CustomColorTemp {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Display_CustomColorTemp"]));
            }
            set {
                this["Display_CustomColorTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection InputSwitch_CustomInputs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InputSwitch_CustomInputs"]));
            }
            set {
                this["InputSwitch_CustomInputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13579")]
        public int Source_Port {
            get {
                return ((int)(this["Source_Port"]));
            }
            set {
                this["Source_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Source_FullscreenDisplayID {
            get {
                return ((string)(this["Source_FullscreenDisplayID"]));
            }
            set {
                this["Source_FullscreenDisplayID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31121")]
        public string Source_VLCPassword {
            get {
                return ((string)(this["Source_VLCPassword"]));
            }
            set {
                this["Source_VLCPassword"] = value;
            }
        }
    }
}
