//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalHomeCinemaManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalHomeCinemaManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule match: {0}.
        /// </summary>
        internal static string FMT_ROUTING_OK {
            get {
                return ResourceManager.GetString("FMT_ROUTING_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Drive Ejected!.
        /// </summary>
        internal static string MSG_DRIVE_EJECTED {
            get {
                return ResourceManager.GetString("MSG_DRIVE_EJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Drive Inserted..
        /// </summary>
        internal static string MSG_DRIVE_INSERTED {
            get {
                return ResourceManager.GetString("MSG_DRIVE_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization complete..
        /// </summary>
        internal static string MSG_INIT_COMPLETE {
            get {
                return ResourceManager.GetString("MSG_INIT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse rules!.
        /// </summary>
        internal static string MSG_PARSE_RULES_ERROR {
            get {
                return ResourceManager.GetString("MSG_PARSE_RULES_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule processing failed!.
        /// </summary>
        internal static string MSG_ROUTING_ERROR {
            get {
                return ResourceManager.GetString("MSG_ROUTING_ERROR", resourceCulture);
            }
        }
    }
}
